import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      <Nav />
    </div>
  );
}
export async function getServerSideProps(context) {
  const genre = context.query;
  console.log("context:", genre);
  return {
    props: {}, // will be passed to the page component as props
  };
}
